const actiontypes = Object.freeze(
    {
        USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
        USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

        USER_LOGOUT: 'USER_LOGOUT',

        FETCH_DATA_TYPE_SUCCESS: 'FETCH_DATA_TYPE_SUCCESS',
        FETCH_DATA_TYPE_FAIL: 'FETCH_DATA_TYPE_FAIL',

        // FETCH_PRODUCT_TABLE_PAGE_SUCCESS: 'FETCH_PRODUCT_TABLE_PAGE_SUCCES',
        // FETCH_PRODUCT_TABLE_PAGE_FAIL: 'FETCH_PRODUCT_TABLE_PAGE_FAIL',
    }

)
export default actiontypes