const actiontypes = Object.freeze(
    {
        USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
        USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',

        USER_LOGOUT: 'USER_LOGOUT',

        FETCH_DATA_TYPE_SUCCESS: 'FETCH_DATA_TYPE_SUCCESS',
        FETCH_DATA_TYPE_FAIL: 'FETCH_DATA_TYPE_FAIL',

        // FETCH_PRODUCT_TABLE_PAGE_SUCCESS: 'FETCH_PRODUCT_TABLE_PAGE_SUCCES',
        // FETCH_PRODUCT_TABLE_PAGE_FAIL: 'FETCH_PRODUCT_TABLE_PAGE_FAIL',

        FETCH_ALL_PRODUCT_BY_TYPE_SUCCESS: 'FETCH_ALL_PRODUCT_BY_TYPE_SUCCESS',
        FETCH_ALL_PRODUCT_BY_TYPE_FAIL: 'FETCH_ALL_PRODUCT_BY_TYPE_FAIL',

        // FETCH_ALL_BANNER_BY_TYPE_SUCCESS: 'FETCH_ALL_BANNER_BY_TYPE_SUCCESS',
        // FETCH_ALL_BANNER_BY_TYPE_FAIL: 'FETCH_ALL_BANNER_BY_TYPE_FAIL'

        GET_DATA_DETAIL_PRODUCT_SUCCESS: 'GET_DATA_DETAIL_PRODUCT_SUCCESS',
        GET_DATA_DETAIL_PRODUCT_FAIL: 'GET_DATA_DETAIL_PRODUCT_FAIL',

        GET_DATA_PRODUCT_BY_SORT_SUCCESS: 'GET_DATA_PRODUCT_BY_SORT_SUCCESS',
        GET_DATA_PRODUCT_BY_SORT_FAIL: 'GET_DATA_PRODUCT_BY_SORT_FAIL',

        ADD_PRODUCT_CART_SUCCESS: 'ADD_PRODUCT_CART_SUCCESS',
        ADD_PRODUCT_CART_FAIL: 'ADD_PRODUCT_CART_FAIL',

        GET_PRODUCT_CART_SUCCESS: 'GET_PRODUCT_CART_SUCCESS',
        GET_PRODUCT_CART_FAIL: 'GET_PRODUCT_CART_FAIL'
    }

)
export default actiontypes